### ISSUE TITLE
Question on special honor

### ISSUE THREAD

**Issue by sherlock55341** [liangrj2014/ISPD24_contest#28]
In the introduction doc of the contest, there is a special honor part. And in this part, runtime plays an important role in the final score. Maybe our router should offer 2 modes for regular routing and early stage routing, so I wonder we can submit 2 routers or 1 router which can perform 2 different routing flows with different shell commands.
Thank you.

**Comment by liangrj2014** [comment]
Thanks for the question! I think one router with two modes sounds great! We will adapt our evaluation flow for it and release the details soon. Thanks!
