### ISSUE TITLE
Question about the runtime

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD24_contest#30]
Hello!
According to the released Alpha and Beta results, the results have runtimes reported as integers. 
However, for certain small cases, the integer precision might not be accurate enough for the runtime.
Therefore, I would like to inquire whether the final evaluation of the competition will consider runtime precision as float or integers.

**Comment by liangrj2014** [comment]
Hi,

Thanks for the question! We will consider runtime as integer in the final evaluation.

**Comment by cai-zhi-jie** [comment]
For example, if the runtime is 4.5, will it be truncated to 4 or rounded to  5?
Will there be 0 runtime for the case with 0,4s runtime?

**Comment by liangrj2014** [comment]
Thanks for the comments! We will use float to record runtime instead
