### ISSUE TITLE
Question about the final benchmark

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD24_contest#31]
Hello!
In the contest introduction: [contest introduction](https://drive.google.com/file/d/1yEgcjHAZOyFHKlfYhzHe8ZeZuefEK2sP/view),
the number of cases in the final benchmark in public and blind are both 7, as shown below:

![image](https://github.com/liangrj2014/ISPD24_contest/assets/73417581/3fd5a069-53b6-453f-b868-fea626f2dc42)

But, in the google drive, there are two Ariane cases.
So, which will be chosen as the final benchmark?

**Comment by liangrj2014** [comment]
Thanks for the questions! You can use both for testing your router. But none of them will be used for final ranking. We will only use the seven blind testcases for final ranking.
