### ISSUE TITLE
The variable type of layerMinLengths, hEdgeLengths, and vEdgeLengths

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD24_contest#7]
In the evaluator.cpp, the layerMinLengths, hEdgeLengths, and vEdgeLengths were treated as double.
```
std::vector<double> layerMinLengths
std::vector<double> hEdgeLengths;
std::vector<double> vEdgeLengths;
```
But are these variables in the db unit, which means they are integers?

**Comment by liangrj2014** [comment]
you are right! They are integers. Sorry for the confusion and the late response! We will update it in the newer version of evaluator
